version: '3'

services:
  web:
    image: node:18
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install && yarn dev:web"
    environment:
      NUXT_PORT: 8000
      NODE_ENV: development
  admin:
    image: node:18
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install && yarn dev:admin"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
